-- require("monokai-pro").setup({
--   transparent_background = true,
-- 
--   terminal_colors = true,
-- 
--   devicons = true, -- highlight the icons of `nvim-web-devicons`
-- 
--   styles = {
--     comment = { italic = false },
--     keyword = { italic = false }, -- any other keyword
--     type = { italic = false }, -- (preferred) int, long, char, etc
--     storageclass = { italic = false }, -- static, register, volatile, etc
--     structure = { italic = false }, -- struct, union, enum, etc
--     parameter = { italic = false }, -- parameter pass in function
--     annotation = { italic = false },
--     tag_attribute = { italic = false }, -- attribute of tag in reactjs
--   },
-- 
--   filter = "spectrum", -- classic | octagon | pro | machine | ristretto | spectrum
-- 
--   ---@param c Colorscheme
--   override = function(c) end,
-- })

-- vim.cmd([[colorscheme monokai-pro]])
